---
# Deployment of our litmus-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmus-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: litmus-service
  replicas: 1
  template:
    metadata:
      labels:
        run: litmus-service
    spec:
      containers:
        - name: litmus-service
          image: keptnsandbox/litmus-service:latest 
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker.keptn.svc.cluster.local/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service.keptn.svc.cluster.local:8080'
        - name: distributor
          image: keptn/distributor:0.7.1
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.events.deployment-finished'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
# Expose litmus-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: litmus-service
  namespace: keptn
  labels:
    run: litmus-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: litmus-service
---
## Subscribe to events via a keptn/distributor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmus-service-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:0.6.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            # listen to all events in sh.keptn. - see https://github.com/keptn/spec/blob/0.1.3/cloudevents.md
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: 'litmus-service'
