---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-litmus-service
  namespace: keptn
  labels:
    name: keptn-litmus-service
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: keptn-litmus-service
  labels:
    name: keptn-litmus-service
rules:
- apiGroups: ["","apps","batch","extensions","litmuschaos.io","openebs.io","storage.k8s.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults","cstorpools","cstorvolumereplicas","configmaps","secrets","pods","pods/exec","pods/log","pods/eviction","jobs","replicasets","deployments","daemonsets","statefulsets","persistentvolumeclaims","persistentvolumes","storageclasses","services","events"]
  verbs: ["create","delete","get","list","patch","update", "deletecollection"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: keptn-litmus-service
  labels:
    name: keptn-litmus-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-litmus-service
subjects:
- kind: ServiceAccount
  name: keptn-litmus-service
  namespace: keptn
---
# Deployment of our litmus-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmus-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: litmus-service
  replicas: 1
  template:
    metadata:
      labels:
        run: litmus-service
    spec:
      serviceAccountName: keptn-litmus-service
      containers:
        - name: litmus-service
          image: keptnsandbox/litmus-service:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.0
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.test.triggered,sh.keptn.event.test.finished'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
# Expose litmus-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: litmus-service
  namespace: keptn
  labels:
    run: litmus-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: litmus-service
